cursor_shape          Underline
cursor_underline_thickness 1
window_padding_width  20

# General Colors
background #0a0a0c
foreground #ffffff
background_opacity 0.95

selection_background #ff2cf1
selection_foreground #000000

cursor #ff2cf1
cursor_text_color #000000

# Normal Colors
color0  #141417
color1  #ff3366
color2  #50fa7b
color3  #f1fa8c
color4  #00f0ff
color5  #ff2cf1
color6  #00f0ff
color7  #f8f8f2

# Bright Colors
color8  #6272a4
color9  #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #38bdf8
color13 #ff60f6
color14 #80f4ff
color15 #ffffff
