#!/bin/sh

_options="󰍁|Lock
|Suspend
󰗽|Logout
󰜉|Reboot
󰐥|Poweroff"

rofi_cmd() {
	rofi -dmenu \
		-p "Goodbye ${USER}" \
		-mesg "Uptime: $(uptime -p | sed -e 's/up //g')" \
		-theme "$HOME"/.config/rofi/themes/powermenu.rasi
}

selected=$(printf '%s\n' "$_options" | cut -d'|' -f1 | rofi_cmd)

if [ -n "$selected" ]; then
    chosen=$(printf '%s\n' "$_options" | awk -F'|' -v sel="$selected" '$1 == sel {print $2}')

    case $chosen in
        "Lock") ScreenLocker ;;
        "Suspend") systemctl suspend ;;
        "Logout") bspc quit ;;
        "Reboot") systemctl reboot ;;
        "Poweroff") systemctl poweroff ;;
    esac
fi
