#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
vmware-user-suid-wrapper &
#bspc config pointer_motion_interval 100
/usr/bin/feh --bg-fill ~/Wallpapers/wallpapersden.com_huawei-4k-stock-abstract_2560x1440.jpg
~/.config/polybar/launch.sh --custom
picom &
#bspc config border_width 0
wmname LG3D &
flameshot &
clipmenud &

# BSPWM Geometry & Border Configuration
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.52

# Neon Color Scheme
bspc config focused_border_color "#ff00ee"
bspc config normal_border_color  "#141417"
bspc config active_border_color  "#00f0ff"
bspc config presel_feedback_color "#ff2cf1"

# Monocle & Tiling Rules
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config single_monocle       false

# Window Rules
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Code desktop='^3' follow=on
bspc rule -a Discord desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a BurpSuitePro desktop='^7'
bspc rule -a Rofi state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Feh state=floating